server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # React Router - vse zahteve preusmeri na index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy na Supervisor API (test supervisor)
    location /api/ {
        proxy_pass http://elits_supervisor_test:1977/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # WebSocket za loge
    location /ws/ {
        proxy_pass http://elits_supervisor_test:1977/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
